### ISSUE TITLE
Post on blog page shows only featured image, worked before

### ISSUE THREAD

**Issue by Yessi66** [lushkant/really-simple-featured-video#10]
Hi Lushkant, I used your plugin along with Divi to showcase mp4 as featured video on archive pages. It worked. But only briefly. Now it doesn't show the video, only the featured image. 
![settingsinpost](https://user-images.githubusercontent.com/99182036/203550684-1e022a87-28b8-442d-a3e3-e84326a869c2.jpg)

I tried again with all the other plugins deactivated, but didn't help. 

Thanks.

**Comment by lushkant** [comment]
Hi there @Yessi66 

Sorry for the late reply, I have just released an update with support for WP core themes and some new beneficial features.
I'll keep track of this in the upcoming updates and hopefully include this at the earliest possible.

I also have a full-time job and don’t get much time out to keep working on this, but for the past week, I’m trying to continue this under my own one-man team.
Hopefully, this makes sense!

**Comment by Yessi66** [comment]
Hi @lushkant, thank you for your reply!
I will check the updates!

Met gezonde groet,




Jessy de Boer
Lisdoddelaan 70
1562 SN Krommenie
06 547 277 40
https://dewpdokter.nl



Op zo 23 apr 2023 om 10:39 schreef Krishna Kant Chourasiya <
***@***.***>:

**Comment by lushkant** [comment]
Hi there @Yessi66 as per the recent release of our Pro addon for this plugin, support for Divi has now been moved to it and will soon be added in the coming months/year.

You can checkout all that Pro has to offer at the plugin settings "Get Pro" tab, in the latest version of the free plugin.

Thank you for support!
