### ISSUE TITLE
Getting Error on my page after recent update

### ISSUE THREAD

**Issue by OcEchebiri** [lushkant/really-simple-featured-video#13]
How can i roll back to the  previous version. I am getting below error:

Warning: filemtime(): stat failed for /home/digitnetstore/domains/digitnetstore.com/public_html/wp-content/plugins/really-simple-featured-video/includes/Compatibility/Themes/Core/Fallback/styles.css in /home/digitnetstore/domains/digitnetstore.com/public_html/wp-content/plugins/really-simple-featured-video/includes/Compatibility/Themes/Fallback/class-compatibility.php on line 44

**Comment by lushkant** [comment]
@OcEchebiri Fixed in v0.7.0
