### ISSUE TITLE
Product page featured video appears repeatedly

### ISSUE THREAD

**Issue by lushkant** [lushkant/really-simple-featured-video#15]
From wp.org forums - https://wordpress.org/support/topic/the-product-page-featured-video-appears-repeatedly/

"Hello, I suddenly have this problem on my website, I apply this plugin in my product page, in fact I have only one product video：https://prnt.sc/XfLI2p-Q-3Ml

Please check what is the cause and tell me how to fix it?"

**Comment by rogercoathup** [comment]
Also seeing this problem

**Comment by bluebee-team** [comment]
Same. See screenshot. No errors in console. In addition to the OP, the featured video also doesn't load.

![Screenshot 2023-08-08 at 11 53 40](https://github.com/smalltowndev/really-simple-featured-video/assets/95026268/5f5cf0e3-683a-42bc-b969-d1e23f3b0719)

**Comment by lushkant** [comment]
> Same. See screenshot. No errors in console. In addition to the OP, the featured video also doesn't load.
> 
> 
> 
> ![Screenshot 2023-08-08 at 11 53 40](https://github.com/smalltowndev/really-simple-featured-video/assets/95026268/5f5cf0e3-683a-42bc-b969-d1e23f3b0719)
> 
> 

Sorry for the delay in reply, but can you please give me a bit more info about the site. Such as the theme, or builder, woo plugin you are using and their versions.

**Comment by rogercoathup** [comment]
The problem appears to arise because the insertion of the video is hooked on `woocommerce_single_product_image_thumbnail_html` (in really-simple-featured-video/includes/Compatability/Plugins/WooCommerce/class-compatability.php)

That filter is called for every attachment in the product gallery (in woocommerce/templates/single-product/product-thumbnails.php)

It appears you are trying to stop multiple inclusions by using a counter variable and checking whether it's set to 0 (line 172).  That check also includes an || $is_loop condition, which I assume returns true, causing the check to always be successful and the video is therefore inserted repeatedly.

**Comment by rogercoathup** [comment]
Note: I tried to ask this as a pre-support question for your paid version of the plugin on woocommerce.com, but got a reply saying it wasn't the same (or even a related plugin).  You might want to correct them on that.

**Comment by lushkant** [comment]
Thank you for taking a look into this @rogercoathup, but the WooCommerce feature is now scheduled for deprecation, in the next version here.
As it is no longer an easy feature to maintain out of my own time, especially now that WooCommerce is moving towards block-based layout, more and more filters and actions are either already removed or going to get removed which were crucial for this plugin to work with Woo.

Here are a few issues for reference -
https://github.com/woocommerce/woocommerce-blocks/issues/3160
https://github.com/woocommerce/woocommerce-blocks/issues/891

And about the premium plugin at Woo Marketplace, that is correct what the Woo team said it is not related. This was an open-source project from my own free time a long time back, and that one on the other hand is a new product and is here to stay, I know this because I also work at the same company that created it and then I suggested the name for it as I wasn't completely over the name of this plugin I was a bit biased.

I'll be closing this issue and any others that are Woo specific.
Hope this makes sense, have a great day :)
