### ISSUE TITLE
How can the plugin to support custom post types?

### ISSUE THREAD

**Issue by Taichang9923** [lushkant/really-simple-featured-video#16]
Dear Sir,

Thanks for sharing this great plugin.  It works well in WordPress posts.

Since I created a few different post types in WordPress using CPT UI, I wonder how this plugin can be used for these own created custom post types? 

PS: I cannot see any custom post type selection from the plugin setting.

**Comment by lushkant** [comment]
@Taichang9923  Added in v0.7.0

**Comment by Taichang9923** [comment]
Thanks for your kind support.
