### ISSUE TITLE
Video should not be the first one

### ISSUE THREAD

**Issue by shovoalways** [lushkant/really-simple-featured-video#23]
If I add a video on a product. It shows first. That is good, but it also replaces the cover photo. because of that everywhere it starts the video and it hampers the website loading time. I think it would be grate if you added an option so I can use the video as another product gallery image and will not hamper the featured image.

**Comment by lushkant** [comment]
Hi there @shovoalways, noted. I'll take this as a feedback in the right direction. I'll be releasing a Pro version very soon, which will have this feature if you wish to utilize it do register your email at our list at hello@smalltowndev.com thank you for your time.
