### ISSUE TITLE
Issues with auto loop

### ISSUE THREAD

**Issue by emeast** [lushkant/really-simple-featured-video#24]
I am using this plugin for a recent events slider. I have the youtube videos embedded on each project just fine, however when the video ends, it pulls up recommended videos through youtube. I've been trying to figure out how to loop this. I have the settings and I've added source code/instruction at the end of the youtube links, and I'm still having the issue of no loop and recommended videos... Would love some insight here. 

[https://test.webbproduction.com] The module is the third one down.

**Comment by lushkant** [comment]
As per i can check at the above mentioned URL, this is no longer being in use. Hope its a better experience next time.
