### ISSUE TITLE
How to use in my custom blog file

### ISSUE THREAD

**Issue by yashborda** [lushkant/really-simple-featured-video#36]
![image](https://github.com/user-attachments/assets/0369ba90-1ba1-45e6-9af2-35c663357181)
I am trying to add my custom-blog.php file to add and show video 
```
<div class="w-700 video-box">
	<?php  echo do_shortcode('[rsfv]'); ?>
 </div>
```
 
Could you help me figure out how to use that? It is not working.

**Comment by lushkant** [comment]
Hey @yashborda if the issue still persists can you please send a support request at support@jetixwp.com for better help on this.
