### ISSUE TITLE
Use Image Product first instead self hosted video in a product on Woocommerce

### ISSUE THREAD

**Issue by Thomson67** [lushkant/really-simple-featured-video#8]
Hi,

I use your plugin who's perfect for me but the only thing i don't understand and modify is that the self hosted video has the priority on the image product when i open a product page.

Can you explain me how to display the Image Product first?

Thanks in advance,
Thomas

**Comment by newaaz** [comment]
I would also like to know how to place a video **after** the images
Thanks (:

**Comment by lushkant** [comment]
Hi there @Thomson67 @newaaz 

Sorry for the late reply, I have just released an update with support for WP core themes and some new beneficial features.
I'll make sure to include this in the upcoming updates, thank you both for your time and request :)

I also have a full-time job and don’t get much time out to keep working on this, but for the past week, I’m trying to continue this under my own one-man team.
Hopefully, this makes sense!

**Comment by lushkant** [comment]
https://github.com/smalltowndev/really-simple-featured-video/issues/15#issuecomment-1702802800
